
version: 0.0
os: linux
files:
  - source: ./hello.py
    destination: /home/ec2-home/hello/
  - source: ./etc/init/mu-minimal-ec2.conf
    destination: /etc/init/

hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 30
  ApplicationStart:
    - location: scripts/start_server
      timeout: 30
